import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header";

const poppins = Poppins({ subsets: ["latin"], display: 'swap', variable: "--font-poppins", weight: ["300", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable + "relative"}>
        <Header />
        <div className="container max-w-[1024px] pb-12">{children}</div>
        </body>
    </html>
  );
}
